version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: e_commerce_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/init_script.sql:/docker-entrypoint-initdb.d/init_script.sql
    env_file:
      - .env

volumes:
  postgres_data:
